# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib raticate.tests
#' @importFrom Rcpp sourceCpp
#' @export
parse <- function(seed) {
    .Call('_raticate_tests_parse', PACKAGE = 'raticate.tests', seed)
}

#' @export
nrow <- function(parsed) {
    .Call('_raticate_tests_nrow', PACKAGE = 'raticate.tests', parsed)
}

#' @export
ncol <- function(parsed) {
    .Call('_raticate_tests_ncol', PACKAGE = 'raticate.tests', parsed)
}

#' @export
row <- function(parsed, i) {
    .Call('_raticate_tests_row', PACKAGE = 'raticate.tests', parsed, i)
}

#' @export
row_subset <- function(parsed, i, first, last) {
    .Call('_raticate_tests_row_subset', PACKAGE = 'raticate.tests', parsed, i, first, last)
}

#' @export
column <- function(parsed, i) {
    .Call('_raticate_tests_column', PACKAGE = 'raticate.tests', parsed, i)
}

#' @export
column_subset <- function(parsed, i, first, last) {
    .Call('_raticate_tests_column_subset', PACKAGE = 'raticate.tests', parsed, i, first, last)
}

#' @export
sparse_row <- function(parsed, i) {
    .Call('_raticate_tests_sparse_row', PACKAGE = 'raticate.tests', parsed, i)
}

#' @export
sparse_row_subset <- function(parsed, i, first, last) {
    .Call('_raticate_tests_sparse_row_subset', PACKAGE = 'raticate.tests', parsed, i, first, last)
}

#' @export
sparse_column <- function(parsed, i) {
    .Call('_raticate_tests_sparse_column', PACKAGE = 'raticate.tests', parsed, i)
}

#' @export
sparse_column_subset <- function(parsed, i, first, last) {
    .Call('_raticate_tests_sparse_column_subset', PACKAGE = 'raticate.tests', parsed, i, first, last)
}

#' @export
rows <- function(parsed) {
    .Call('_raticate_tests_rows', PACKAGE = 'raticate.tests', parsed)
}

#' @export
rows_subset <- function(parsed, first, last) {
    .Call('_raticate_tests_rows_subset', PACKAGE = 'raticate.tests', parsed, first, last)
}

#' @export
columns <- function(parsed) {
    .Call('_raticate_tests_columns', PACKAGE = 'raticate.tests', parsed)
}

#' @export
columns_subset <- function(parsed, first, last) {
    .Call('_raticate_tests_columns_subset', PACKAGE = 'raticate.tests', parsed, first, last)
}

#' @export
sparse_rows <- function(parsed) {
    .Call('_raticate_tests_sparse_rows', PACKAGE = 'raticate.tests', parsed)
}

#' @export
sparse_rows_subset <- function(parsed, first, last) {
    .Call('_raticate_tests_sparse_rows_subset', PACKAGE = 'raticate.tests', parsed, first, last)
}

#' @export
sparse_columns <- function(parsed) {
    .Call('_raticate_tests_sparse_columns', PACKAGE = 'raticate.tests', parsed)
}

#' @export
sparse_columns_subset <- function(parsed, first, last) {
    .Call('_raticate_tests_sparse_columns_subset', PACKAGE = 'raticate.tests', parsed, first, last)
}

#' @export
rowsums <- function(parsed) {
    .Call('_raticate_tests_rowsums', PACKAGE = 'raticate.tests', parsed)
}

#' @export
rowsums_manual <- function(parsed) {
    .Call('_raticate_tests_rowsums_manual', PACKAGE = 'raticate.tests', parsed)
}

