on:
  push:
    branches:
      - master
  pull_request:

name: Check CMake install

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Install tatami
      run: |
        git clone https://github.com/tatami-inc/tatami dep-tatami --depth=1
        cd dep-tatami
        cmake -S . -B build -DTATAMI_TESTS=OFF
        sudo cmake --install build

    - name: Install tatami-chunked
      run: |
        git clone https://github.com/tatami-inc/tatami_chunked dep-tatami_chunked --depth=1
        cd dep-tatami_chunked
        cmake -S . -B build -DTATAMI_CHUNKED_TESTS=OFF
        sudo cmake --install build

    - name: Install manticore
      run: |
        git clone https://github.com/tatami-inc/manticore dep-manticore --depth=1
        cd dep-manticore
        cmake -S . -B build 
        sudo cmake --install build

    - name: Configure the build
      run: cmake -S . -B build -DTATAMI_R_FETCH_EXTERN=OFF

    - name: Install the library
      run: sudo cmake --install build

    - name: Test downstream usage
      run: |
        mkdir _downstream
        touch _downstream/source.cpp
        cat << EOF > _downstream/CMakeLists.txt
        cmake_minimum_required(VERSION 3.24)
        project(test_install)
        add_executable(whee source.cpp)
        find_package(tatami_tatami_r)
        target_link_libraries(whee tatami::tatami_r)
        EOF
        cd _downstream && cmake -S . -B build
